CREATE TABLE CUSTOMER (
	FirstName	INTEGER,
	LastName	INTEGER,
	email	INTEGER,
	CustomerID	INTEGER	NOT NULL,
PRIMARY KEY (CustomerID) );

CREATE TABLE PRODUCT (
	Price	INTEGER,
	ProductID	INTEGER	NOT NULL,
PRIMARY KEY (ProductID) );

CREATE TABLE Buys (
	FK1_ProductID	INTEGER	NOT NULL,
	FK2_CustomerID	INTEGER	NOT NULL,
PRIMARY KEY (FK1_ProductID, FK2_CustomerID) );

ALTER TABLE Buys ADD FOREIGN KEY (FK1_ProductID) REFERENCES PRODUCT (ProductID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Buys ADD FOREIGN KEY (FK2_CustomerID) REFERENCES CUSTOMER (CustomerID) ON DELETE CASCADE ON UPDATE CASCADE;

